---
###############################################################################
# This playbook utilizes the ios_command ansible module to execute a set of
# show commands against the cisco ios devices defined in the [cisco_xe]
# group within the hosts file.   The command executes a list of show commands
# and saves the result of each command into the output variable.
#
# The output variable is then displayed as part of the playbook run
#
# The contents of the output variable are then saved using two different methods.
# device-output.txt has the raw output format which is a JSON data structure
# device.cfg saves the results of the first command sent which in this case
# is the show run command (hence the .cfg file type)
#
# EXECUTION:
# ansible-playbook -i hosts ios_show_lab.yml
###############################################################################

- hosts: cisco_xe
  connection: local
  gather_facts: False
  ignore_errors: yes

  vars:
    cli:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        timeout: 30

  tasks:
    - name: Iterate over show commands
      ios_command:
        commands: "{{ item }}"
        provider: "{{ cli }}"

      with_items:
      - "show run"
      - "show version"
      - "show inventory"
      - "show module"
      - "show cdp nei"
      - "show cdp nei det"
      - "show vlan"
      - "show span"
      - "show int"
      - "show int status"
      - "show int trunk"
      - "show int capabilities"
      - "show etherchannel sum"
      - "show swi"
      - "show swi detail"
      - "show env all"
      - "show power inline"
      - "show swi neighbors"
      - "show license right-to-use"a
      - "dir"
      - "show ip int br"
      - "show ip route"
      - "show ip route sum"
      - "show ip ospf nei"
      - "show ip bgp sum"
      - "show ip arp"
      - "show ip dhcp snooping"
      - "show mac address-table"


      register: output

    - debug: var=output

    - local_action: copy content="{{ output.results }}" dest="./logs/{{ inventory_hostname }}-output.txt"
    - local_action: copy content="{{ output.results.0.stdout.0 }}" dest="./logs/{{ inventory_hostname }}.cfg"

    - name: Generate Device Show Command File(s)
      template: src=./templates/show-commands-template.j2
                  dest=./logs/{{ inventory_hostname }}.cfg

      with_items:
        - "{{ output }}"
