---

- name: Collect device facts with the ios_facts module and display selected values
  # hosts: "{{ inventory | default('all') }}"
  hosts: cisco_xe
  gather_facts: false
  connection: local
  ignore_errors: yes

  vars:
    all_facts: []
    cli:
        host: "{{ inventory_hostname  }}"
        username: "{{ username }}"
        password: "{{ password }}"

  tasks:
    - name: Gather Facts with the facts module
      ios_facts:
        provider: "{{ cli }}"

      register: facts_output

    - debug: var=facts_output.ansible_facts.ansible_net_hostname
    - debug: var=facts_output.ansible_facts.ansible_net_version
    - debug: var=facts_output.ansible_facts.ansible_net_model

