---

- name: Collect device facts with the ios_facts module and display selected values
  # hosts: "{{ inventory | default('all') }}"
  hosts: nxos
  gather_facts: false
  ignore_errors: yes


  tasks:
    - name: Check Group Vars
      debug:
        msg: "connection type is {{ ansible_connection }} and os is {{ ansible_network_os}}"

    - name: Gather Facts with the NXOS facts module
      nxos_facts:
        gather_subset: all
      when: ansible_network_os == 'nxos'

      register: facts_output

    - debug: var=facts_output.ansible_facts.ansible_net_hostname
    - debug: var=facts_output.ansible_facts.ansible_net_version
    - debug: var=facts_output.ansible_facts.ansible_net_model

    - name: Display debug module msg with all variables of interest
      debug:
        msg: "Device with hostname {{ facts_output.ansible_facts.ansible_net_hostname }} is of model type
        {{ facts_output.ansible_facts.ansible_net_model }} running software version {{ facts_output.ansible_facts.ansible_net_version }}"